spring:
  application:
    name: BE_SmartNote
  datasource:
    url: "jdbc:mysql://localhost:3306/smart_note"
    username: root
    password:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"